apiVersion: apps/v1
kind: Deployment
metadata:
  name:asp-dotnet-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels: 
        app: dotnet-app
    spec:
      containers:
      - name: aspcontainer
        image: acrangular.azurecr.io/ASP-app:latest
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-svc
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer