name: Trigger auto deployment for github-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/github-aca-AutoDeployTrigger-ed26b724-0290-4085-8193-4592c217b357.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GITHUBACA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: demoacr4.azurecr.io
          registryUsername: ${{ secrets.GITHUBACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GITHUBACA_REGISTRY_PASSWORD }}
          containerAppName: github-aca
          resourceGroup: D-rg
          imageToBuild: demoacr4.azurecr.io/github-aca:${{ github.sha }}
          

     

